# Generated by Django 4.1 on 2022-10-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedUsersModel',
            fields=[
                ('user_id', models.CharField(max_length=1023, primary_key=True, serialize=False)),
                ('subscription_expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='UserPrivilegeModel',
            fields=[
                ('user_id', models.CharField(max_length=1023, primary_key=True, serialize=False)),
                ('privilege', models.IntegerField(default=0)),
                ('created_by', models.CharField(max_length=1023)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
